---
title: "Marvel Data"
output: html_document
---

#Changing directory
```{r}
setwd("~/Desktop/Marvel")
```

#Loading data set
```{r}
avengers<-read.csv('avengers.csv')
avengers<-avengers[,-1]
head(avengers)
```
#Loading required libraries
```{r}
library(dplyr)
library(ggplot2)
library(dplyr)
```

#Explatory
```{r}

avengers %>% 
  arrange(desc(Appearances))
  
#Most of the characters were male
#Didn't recognize a lot of the characters because of their full names


```

#Take a look at a top 25
```{r}

top_25<-avengers %>% 
          arrange(desc(Appearances)) %>%
          slice(1:25)

top_25

table(top_25$Death1)
#More than 50% of the top 25 characters have died at least once ~60%

table(top_25$Return1)
#Of the ones who died once, ~87% returned 

table(top_25$Death2)
#Of those who have died once, 3 characters died again ~12%

table(top_25$Return2)
#Of those who have died again, ~66.67% returned

table(top_25$Death3)
#none of them died again! 2x deaths is a maximum

avengers %>% 
    arrange(desc(Appearances)) %>%
    slice(1:25)

```
#Assigning score each time a character dies
```{r}

score<-rep(NA,nrow(avengers))

for(j in 1:nrow(avengers)){
  
    i<-0

  if(avengers$Death1[j] == "YES")
    i<-i+1
  
  if(avengers$Death2[j] == "YES")
    i<-i+1

  if(avengers$Death3[j] == "YES")
    i<-i+1
  
  if(avengers$Death4[j] == "YES")
    i<-i+1
  
  if(avengers$Death5[j] == "YES")
    i<-i+1
  
  score[j]<-i

}
score
table(score)
```
#Assigning score to when a character is revived
```{r}

library(varhandle)

avengers<-cbind(avengers,score)
data_graph<-avengers[,c(1,2,10:19,21)]
data_graph<-data_graph[!data_graph$Name.Alias=="",]


return<-data_graph[,c(3:12)]

return$Death1<-unfactor(return$Death1)
return$Death2<-unfactor(return$Death2)
return$Death3<-unfactor(return$Death3)
return$Death4<-unfactor(return$Death4)
return$Death5<-unfactor(return$Death5)

return$Return1<-unfactor(return$Return1)
return$Return2<-unfactor(return$Return2)
return$Return3<-unfactor(return$Return3)
return$Return4<-unfactor(return$Return4)
return$Return5<-unfactor(return$Return5)

for(i in 1:nrow(return)){
    if(return$Death1[i]=="YES"){
      return$Death1[i]<-1
    }else{
      return$Death1[i]<-0
    }
    
    if(return$Death2[i]=="YES"){
      return$Death2[i]<-1
    }else{
      return$Death2[i]<-0
    }

    if(return$Death3[i]=="YES"){
      return$Death3[i]<-1
    }else{
      return$Death3[i]<-0
    }

    if(return$Death4[i]=="YES"){
      return$Death4[i]<-1
    }else{
      return$Death4[i]<-0
    }

    if(return$Death5[i]=="YES"){
      return$Death5[i]<-1
    }else{
      return$Death5[i]<-0
    }

    if(return$Return1[i]=="YES"){
      return$Return1[i]<-1
    }else{
      return$Return1[i]<-0
    }

    if(return$Return2[i]=="YES"){
      return$Return2[i]<-1
    }else{
      return$Return2[i]<-0
    }

    if(return$Return3[i]=="YES"){
      return$Return3[i]<-1
    }else{
      return$Return3[i]<-0
    }

    if(return$Return4[i]=="YES"){
      return$Return4[i]<-1
    }else{
      return$Return4[i]<-0
    }

    if(return$Return5[i]=="YES"){
      return$Return5[i]<-1
    }else{
      return$Return5[i]<-0
    }
}

return$Death1<-as.numeric(return$Death1)
return$Death2<-as.numeric(return$Death2)
return$Death3<-as.numeric(return$Death3)
return$Death4<-as.numeric(return$Death4)
return$Death5<-as.numeric(return$Death5)

return$Return1<-as.numeric(return$Return1)
return$Return2<-as.numeric(return$Return2)
return$Return3<-as.numeric(return$Return3)
return$Return4<-as.numeric(return$Return4)
return$Return5<-as.numeric(return$Return5)

colSums(return)

return<-colSums(return)

return$Death1<-69-46
return$Death2<-16-8
return$Death3<-1
return$Death4<-0
return$Death5<-0

return<-data.frame((unlist(return)))

classifier<-c("Stayed Dead","Revived","Stayed Dead","Revived","Stayed Dead","Revived","Stayed Dead","Revived","Stayed Dead","Revived")
return<-data.frame(cbind(return,classifier))
colnames(return)<-c('Count','Classifier')

return$DeathType<-c(rep("Death 1",2),rep("Death 2",2),rep("Death 3",2), rep("Death 4",2), rep("Death 5",2))

library(reshape2)

melt_return<-melt(return)
melt_return$index<-factor(rownames(return), levels=rownames(return))

melt_return$Classifier<-factor(melt_return$Classifier)
```
Visualization 1
```{r}
ggplot(melt_return, aes(x=DeathType,y=value)) +
    geom_col(aes(position="stack", stat="identity", fill=Classifier))+ ggtitle("Revival Rate")

```
Visualization 2
```{r}
data_graph$score<-as.factor(data_graph$score)

table(avengers$Death1=="YES")

table(data_graph$score)

pie<-table(data_graph$Death1=="NO")

pie<-data.frame(matrix(c("Died Atleast Once","Never Died",63,100),nrow=2))
colnames(pie)<-c("Status","Count")

ggplot(pie, aes(x = "", y = Count, fill = Status)) +
  geom_bar(width = 1, stat = "identity", color = "white") +
  coord_polar("y", start = 0)+
  ggtitle("Proportion of Deaths in the Avengers")+
  theme_void()
```

Visualization 3
```{r}
library(ggthemes)
ggplot(data_graph,aes(x=score))+geom_bar(aes(fill=score),position="dodge")+theme_tufte()+ggtitle("Death in the Avengers") +
  xlab("Times Characters Died") + ylab("Number of Characters")
```

Visualization 4
```{r}

ggplot(avengers, aes(x=Death1, y=Appearances)) + geom_boxplot() +ggtitle("Appearance vs Death")

```

Comparing difference in two groups
```{r}

t.test(Appearances~Death1, data=avengers)

```

```{r}

avengers[order(avengers$Appearances, decreasing=TRUE),]

```